### ISSUE TITLE
Environment variable 'PYNGUIN_DANGER_AWARE' not set.

### ISSUE THREAD

**Issue by vballestrini** [se2p/pynguin#14]
Hi!
I have tried to run 
`pynguin`

and i am getting this

`Environment variable 'PYNGUIN_DANGER_AWARE' not set..`
`Aborting to avoid harming your system..`
`Please refer to the documentation.`
`(https://pynguin.readthedocs.io/en/latest/user/quickstart.html).`
`to see why this happens and what you must do to prevent it.`

Am I doing something wrong on setup?

**Comment by stephanlukasczyk** [comment]
Hi @vballestrini ,

Thank you for your interest in Pynguin. With yesterday's [release 0.9.2](https://github.com/se2p/pynguin/releases/tag/v0.9.2), Pynguin requires you to set the environment variable `PYNGUIN_DANGER_AWARE` as the error message indicates.

The reason for that is that Pynguin will execute the module it generates tests for. If that module contains code that could harm your system, by executing it, Pynguin could cause harm to your system, e.g., delete files. To prevent this happening accidentially, we've added this feature. You can find a more detailed description in the [documentation](https://pynguin.readthedocs.io/en/latest/user/quickstart.html).

Best,
  Stephan
