### ISSUE TITLE
Docker build issues

### ISSUE THREAD

**Issue by MBA76** [se2p/pynguin#19]
Hi,

I want use pynguin as a docker container. I tried to build the dockerfile which is in the repository.("`docker build  --tag pynguin .`") but is did not build. The reason; Errors related to "poetry".. 

![image](https://user-images.githubusercontent.com/22763099/147546576-8f2253cf-6cd6-4d36-87b6-2870a7b71bfe.png)

![image](https://user-images.githubusercontent.com/22763099/147546527-d2f30716-9cf1-43ea-af95-050571f6cdbe.png)

![image](https://user-images.githubusercontent.com/22763099/147546451-68fed432-5013-4e2c-913b-957316c77c07.png)

I copied pymyproject.toml, README.md and pynguin folder whic is in the repo to the dokcer folder. After; i tryed build ,and builded successfull. I tryed docker run with volumes parameters. The container gave the following as output
![image](https://user-images.githubusercontent.com/22763099/147548134-5e4049bd-49c3-4cd9-836f-426b9156f011.png)

where is the i do mistakes, can your help me?.

**Comment by stephanlukasczyk** [comment]
I am not sure about the exact reason—I am by far no Docker expert.  I assume this might be related to the fact that the `Dockerfile` is stored in the `docker` directory.  If I run

```
docker build --tag pynguin . -f ./docker/Dockerfile
```

Docker builds the container as expected, so there is no need to copy around files.  To execute the container then, I used the following command line (with line-breaks for better readability):

```
docker run \
    -v /path/to/checkout/of/pynguin/docs/source/_static:/input:ro \
    -v /tmp:/output \
    -v /tmp:/package:ro \
    pynguin \
        --project-path /input \
        --output-path /output \
        --module-name example \
        -v
```

Please note that I bind the `/output` directory of the container to `/tmp`, which works on Linux/macOS, but might not work on Windows.  Please further note, that the Pynguin Docker container expects a directory that contains a file `package.txt` to be mounted to `/package` (the third `-v` option).  For this example, the file can be empty (I just did `touch /tmp/package.txt`); if the module you want to generate requires some dependencies it is necessary to specify those in the `package.txt` file (it will be used by `pip install -r /package/package.txt` inside the container).

The other options I am using above are taken from the [quickstart guide](https://pynguin.readthedocs.io/en/latest/user/quickstart.html#a-simple-example).
