### ISSUE TITLE
AssertionError when using LINE Coverage

### ISSUE THREAD

**Issue by JoaoMaio** [se2p/pynguin#32]
I copied "queue_example.py" from the quickstart guide on https://pynguin.readthedocs.io/en/stable/user/quickstart.html.

When i try to get the coverage report "LINE i get the error:

![image](https://user-images.githubusercontent.com/73291213/204110503-ff8f5399-b259-450c-ad52-8a9761f6774c.png)

Commands used: 
pynguin --project-path ../Badge5 --output-path ./tmp/pynguin-results --module-name main -v --create-coverage-report True --seed 1629381673714481067 --coverage_metrics LINE

pynguin --project-path ../Badge5 --output-path ./tmp/pynguin-results --module-name main -v --create-coverage-report True --seed 1629381673714481067 --coverage_metrics BRANCH LINE

I just followed the guide. What am I doing wrong?

**Comment by Wooza** [comment]
Sorry for the inconvenience. The default algorithm (DynaMOSA) only works with branch coverage as of now.
Choosing a different algorithm, e.g., `--algorithm MOSA`, should work.

**Comment by JoaoMaio** [comment]
Thank you for your fast response and thank you for the help. MOSA did work
