### ISSUE TITLE
[Push-Request] Add minimum coverage

### ISSUE THREAD

**Issue by Kucki2018** [se2p/pynguin#44]
There are many programs that do not achieve 100% coverage, so Pynguin runs for a very looong time.
Therefore, the user should be able to decide if they want to reach a certain minimum coverage (e.g. 75%) and if the coverage does not increase (e.g. same coverage over 10 iterations) after that minimum, the program should stop.

**Comment by stephanlukasczyk** [comment]
Thanks for the idea and the PR.  To keep things concise, I'll close this issue and suggest to keep all discussions in the PR #45
