### ISSUE TITLE
Clarification on pynguin's potential to cause serious harm

### ISSUE THREAD

**Issue by poneill** [se2p/pynguin#47]
Currently the docs make very prominent mention of the fact that pynguin can cause serious harm to your system, and even requires the user to sign a waiver by setting an env variable acknowledging this.  What exactly does this mean?

As far as I can tell (I may be wrong) it just means that pynguin executes the module it's generating tests for instead of analyzing the code statically.  If that's correct, then pynguin seems no more or less dangerous than python unit testing conventions themselves: if I want to test a module `foo` then my test script `test_foo.py` will contain a line like `from foo import bar` which will execute top-level code is in `foo.py` (excepting the `if __name__ == "__main__"` block if applicable).

So, is pynguin any more dangerous than e.g. pytest?  Further clarification of this point in the docs and in the warning message when pynguin is run with `PYNGUIN_DANGER_AWARE` unset would be welcome.

Thanks!

**Comment by stephanlukasczyk** [comment]
Hi and thank you for your interest and question.

You are in fact right, Pynguin does not cause more harm than, say, pytest.  However, when we published Pynguin there was some discussion (on Reddit, IIRC) from which we (among other things) gained that many people are not aware of the fact that a test generation such as Pynguin actually needs to execute the module under test.  People are aware that this is the fact for pytest but presumably some are not for test generators.  Thus, we added this prominent warning and the waiver variable.

One problem that could make Pynguin more dangerous than pytest is the fact, that it will create random inputs for the subject under test.  When you have tests you want to execute with pytest, you could look at them and in most cases read from the code whether it does something potentially dangerous. This can, however, not easily be done in the Pynguin case.
