### ISSUE TITLE
Small typo?

### ISSUE THREAD

**Issue by lephantriduc** [se2p/pynguin#75]
I think there is a small typo in the section "A more complex example" in Quickstart.
Shouldn't the function be
```python
def empty(self) -> bool:
        return self.size == 0
```
It is supposed to return True if the Queue is empty, isn't it?
<img width="736" alt="SCR-20240913-smlb" src="https://github.com/user-attachments/assets/e337659a-067e-4b27-b250-4312415c75d6">
[Link](https://pynguin.readthedocs.io/en/latest/user/quickstart.html#a-simple-example:~:text=return%20self.size%20!%3D%200)

**Comment by stephanlukasczyk** [comment]
Fixed in fdab13b
