### ISSUE TITLE
I want to test flask package with pynguin, however pynguin cannot deal with relative imports (i.e., cannot import relative modules of flask). Can you give me some advice on how to solve this problem?

### ISSUE THREAD

**Issue by khangtran2020** [se2p/pynguin#80]
I want to test flask package with pynguin, however pynguin cannot deal with relative imports (i.e., cannot import relative modules of flask). Can you give me some advice on how to solve this problem?

**Comment by stephanlukasczyk** [comment]
Could you provide me a minimal working example, please, that exhibits the behaviour?  I have zero experience with Flask, thus need something to work with.  Please also specify versions of Python, Pynguin, and dependencies, as well as everything else that would be needed to reproduce the issue.

**Comment by Wooza** [comment]
AFAIK, Pynguin adds the directory specified with 'project-path' to sys.path. So I think you have to use the following command for your example:
`pynguin --project-path ./src/ --output-path ../test --module-name flask.cli`

**Comment by khangtran2020** [comment]
I ran as suggested, and it seems like it no longer has that problem. Thank you very much for your help. I really appreciate it.
